https://doc.rust-lang.org/book/ch11-00-testing.html

# Writing Automated Tests
プログラムの正当性は, 「どこまで自分のコードが（自分の）意図していることをしているか」

- 例として, 渡された何かの数値に2を足すadd_twoという関数を書く
  - コンパイラは「Stringの値や無効な参照をこの関数に渡していないかなどを確かめる」ことはできる
  - 「引数に10を足したり, 50を引いたりするのではなく, 引数に2を足していること」は確認できない
- （コンパイラで確認できないことを確認するために）add_two関数に3を渡した時に, 戻り値は5であることをアサーションするようなテストを書く

以降:

- テストを書く際に利用可能になるアノテーションとマクロについて
- テストを実行するのに提供されているオプションと標準の動作
- さらにテストをユニットテストや統合テストに体系化する方法

# How to Write Tests
test属性, いくつかのマクロ, should_panic属性を使って

- 必要なデータや状態をセットアップする
- テスト対象のコードを走らせる
- 結果が想定通りであることをアサーション

### The Anatomy of a Test Function

- テスト実装者はtest属性で注釈された関数（fnの前に`#[test]`を付け加えた関数）を作る.
- `cargo test`コマンドでテストを実行したら, コンパイラはtest属性で注釈された関数を走らせるテスト用バイナリをビルドし,  各テスト関数が通過したか失敗したかを報告

新しいライブラリプロジェクトをCargoで作ると, テスト関数付きのテストモジュールが自動的に生成される:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

- `#[test]` 属性を付与していないとテストとして実行されない.
- ignore/filter については11.2章
- measured: benchmark test は独学でやれとのこと
- Doc-tests: documentation test は14章

テスト関数は２つ書くこともできる.

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn exploration() {
        assert_eq!(2 + 2, 4);
    }
    #[test]
    fn another() {
        panic!("Make this test fail");
    }
}
```

### Checking Results with the assert! Macro
多数の他言語と同じく真偽値となるような引数を assert! マクロに与える.
引数の評価結果が true なら pass し false なら fail する.

```rust
#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}
impl Rectangle {
    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}
#[cfg(test)]
mod tests {
    use super::*;// use outer modules
    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle {
            width: 8,
            height: 7,
        };
        let smaller = Rectangle {
            width: 5,
            height: 1,
        };
        assert!(larger.can_hold(&smaller)); // true or false
    }
    #[test]
    fn smaller_cannot_hold_larger() {
        let larger = Rectangle {
            width: 8,
            height: 7,
        };
        let smaller = Rectangle {
            width: 5,
            height: 1,
        };

        assert!(!smaller.can_hold(&larger));
    }
}
```

上記では Rectangle インスタンス larger と smaller に対して can_hol dを呼び出し結果を確認している. このテストはパスする. tests 外のモジュールを使うため global import を使用（`use super::*;`）している. 

コードにバグを導入すれば assert によりテストは失敗する.
例えば次のように出力.

```
running 2 tests
test tests::larger_can_hold_smaller ... FAILED
test tests::smaller_cannot_hold_larger ... ok

failures:

---- tests::larger_can_hold_smaller stdout ----
thread 'main' panicked at 'assertion failed: larger.can_hold(&smaller)', src/lib.rs:28:9
(スレッド'main'はsrc/lib.rs:28:9の'assertion failed: larger.can_hold(&smaller)'でパニックしました)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

failures:
    tests::larger_can_hold_smaller

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### Testing Equality with the assert_eq! and assert_ne! Macros

- assert!マクロは, ==式の値がfalseになったことしか示さない
- assert_eq!とassert_ne!マクロで等値性をテストする.
  - アサーションが失敗したら期待値と実際の値の二つの値を出力

```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
    // a + 3
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_adds_two() {
        assert_eq!(4, add_two(2));
    }
}
```

コメントアウトされたほう（a + 3）を採用するとテストが失敗し,
次のように出力する.

```
running 1 test
test tests::it_adds_two ... FAILED

failures:

---- tests::it_adds_two stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `5`', src/lib.rs:11:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

failures:
    tests::it_adds_two

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

- assert_eq!マクロ
  - （一般に）アサーションを行う関数の引数を expectedとactualと呼ぶ
  - 引数を指定する順序が問題になる言語やテストフレームワークもある
  - Rustでは, アサーションを行う関数の引数をleftとrightと呼ぶ
  - 期待する値とテスト下のコードが生成する値を指定する順序は好きにして良い
- assert_ne!マクロ
  - 与えた2つの値が等しくなければ通り, 等しければ失敗
  - 値が何になるだろうか確信が持てないけれども, コードが意図した通りに動いていれば, 確実にこの値にはならないだろうとわかっているような場合に有用
  - 例：入力を加工して出力する関数（出力内容は曜日に応じて変化する）. 入力と出力が等しくないことを確認するのに有用
- 比較対象の値はPartialEqとDebugトレイトを実装する必要がある
  - 自分で定義した構造体やenumは注意が必要
  - 引数をデバッグフォーマットを使用してプリントするためにDebugを実装すべき
  - 値の比較のためにPartialEqを実装すべき
  - 通常, 単純に構造体やenum定義に `#[derive(PartialEq, Debug)]` という注釈を追加するだけで済む

### Adding Custom Failure Messages

- assert!の1つの必須引数の後に, あるいはassert_eq!とassert_ne!の2つの必須引数の後に指定された引数はすべてformat!マクロに渡される
  - {}プレースホルダーを含むフォーマット文字列と, {}を置換する何らかの値を渡すことが可能
  - format!マクロについては第8章で議論した

```rust
pub fn greeting(name: &str) -> String {
    format!("Hello {}!", name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greeting_contains_name() {
        let result = greeting("Carol");
        // assert!(result.contains("Carol")); // カスタムメッセージを含めない書き方
        assert!( // カスタムメッセージを含める書き方
            result.contains("Carol"),
            "Greeting did not contain name, value was `{}`", // {}プレースホルダーを含むフォーマット文字列
            result // {}を置換する何らかの値（複数可）
        );
    }
}
```

上記の例だと次のように出力される.

```
running 1 test
test tests::greeting_contains_name ... FAILED

failures:

---- tests::greeting_contains_name stdout ----
thread 'main' panicked at 'Greeting did not contain name, value was `Hello!`', src/lib.rs:12:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Checking for Panics with should_panic

- 想定通りにコードがエラー状態を扱っていることを確認したい.
  - 例えば, 第9章のリスト9-10で生成したGuess型
  - Guessのインスタンスは1から100の範囲の値しか含まないという保証に依存しており, その範囲外の値でGuessインスタンスを生成しようとするとパニックする

```rust
pub struct Guess {
    value: i32,
}
impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            //予想値は1から100の間でなければなりませんが, {}でした。
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }
        Guess { value }
    }
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        Guess::new(200); // panic する値を入れてインスタンスを作ろうとする
    }
}
```

上記の出力例.

```
running 1 test
test tests::greater_than_100 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests guessing_game
```

バグを導入すると次のようになる.

```
running 1 test
test tests::greater_than_100 ... FAILED

failures:

---- tests::greater_than_100 stdout ----
note: test did not panic as expected

failures:
    tests::greater_than_100
```

- should_panicのテストは, 起きると想定していたもの以外の理由でテストがパニックしても通る
  - should_panic属性にexpected引数を追加することでpanicのメッセージに対して期待値を記述できる. つまり想定するpanicの理由を指定できる

```rust
pub struct Guess {
    value: i32,
}
impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 {
            panic!(
                "Guess value must be greater than or equal to 1, got {}.",
                value
            );
        } else if value > 100 {
            panic!(
                "Guess value must be less than or equal to 100, got {}.",
                value
            );
        }
        Guess { value }
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    // 想定するエラーメッセージの一部
    #[should_panic(expected = "Guess value must be less than or equal to 100")]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

上記はパニックメッセージの一部だけを書いたが全体を指定してもよい.
上記にバグを導入してテストが失敗するようにすると次の出力となる.

```
running 1 test
test tests::greater_than_100 ... FAILED

failures:

---- tests::greater_than_100 stdout ----
thread 'main' panicked at 'Guess value must be greater than or equal to 1, got 200.', src/lib.rs:13:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
note: panic did not contain expected string
      panic message: `"Guess value must be greater than or equal to 1, got 200."`,
 expected substring: `"Guess value must be less than or equal to 100"`

failures:
    tests::greater_than_100
```

上記を見ればパニックメッセージをもとにバグの在り処を特定できる.

### Using Result<T, E> in Tests
テスト関数の戻り値を Result にすることも可能.
この場合 `?` 演算子を使えるようになるが, `#[should_panic]` は使えなくなる.

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

# Controlling How Tests Are Run
cargo testで使用できるいろんなオプション.

- 既定動作
  - テストを全て並行に実行
  - テスト実行中に生成された出力をキャプチャして出力が表示されるのを防ぎ
  - テスト結果に関係する出力を読みやすくする
- オプションはcargo testにかかるもの, 出来上がったテストバイナリにかかるものの2種
  - cargo testにかかる引数を `--` という区分記号の後に列挙し, それからテストバイナリにかかる引数を列挙
  - 例：`cargo test --help` と `cargo test -- --help` の出力は別物

### Running Tests in Parallel or Consecutively

- 複数のテストを実行するとき, 標準では, スレッドを使用して並行に走る
  - テストが, 共有された環境（現在の作業対象ディレクトリや環境変数など）や他のテストに依存しないようにする
  - 例えば, 各テストがディスクにtest_output.txtというファイルを作成し, 何らかのデータを書き込むコードを走らせる場合
  - 各テストが異なるファイルに書き込むようにする. あるいは一度に一つのテストを実行

１度にひとつだけ実行するには次のようにする.

```
$ cargo test -- --test-threads=1
```

### Showing Function Output

- テストが通ると, Rustのテストライブラリは標準出力に出力されたものを全てキャプチャする
  - 例えば, テストでprintln!を呼び出してテストが通ると, println!の出力は, 端末に表示されない
  - テストが通ったことを示す行しか見られない
- テストが失敗すれば, 残りの失敗メッセージと共に, 標準出力に出力されたものが全て見える

```rust
fn prints_and_returns_10(a: i32) -> i32 {
    println!("I got the value {}", a); // テストに成功するとこのメッセージは出力されない
    10
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn this_test_will_pass() {
        let value = prints_and_returns_10(4);
        assert_eq!(10, value); // 成功; println の内容を出力しない
    }
    #[test]
    fn this_test_will_fail() {
        let value = prints_and_returns_10(8);
        assert_eq!(5, value); // 失敗; println の内容を出力する
    }
}
```

出力：

```
running 2 tests
test tests::this_test_will_pass ... ok
test tests::this_test_will_fail ... FAILED

failures:

---- tests::this_test_will_fail stdout ----
        I got the value 8
thread 'tests::this_test_will_fail' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `10`', src/lib.rs:19:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::this_test_will_fail
```

`--nocapture` オプションで出力キャプチャを無効化できる.

```
$ cargo test -- --nocapture
```

オプション無しの場合と違い, **テスト結果表示前に** println! の内容が出力されるようになる.

```
running 2 tests
I got the value 4
I got the value 8
test tests::this_test_will_pass ... ok
thread 'tests::this_test_will_fail' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `10`', src/lib.rs:19:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test tests::this_test_will_fail ... FAILED

failures:

failures:
    tests::this_test_will_fail
```

`--test-threads=1` 指定時.

```
running 2 tests
test tests::this_test_will_fail ... I got the value 8
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `10`', src/lib.rs:24:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
test tests::this_test_will_pass ... I got the value 4
ok

failures:

failures:
    tests::this_test_will_fail

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

## Running a Subset of Tests by Name

### Running Single Tests
引数に **テスト名の一部** を渡すことで特定のテストだけを実行できる.
ただし引数は１つしか渡せない（最初のものだけが有効になる）.
上記の例なら以下で１つだけテストを実行可能.

```
$ cargo test this_test_will_pass
```

### Filtering to Run Multiple Tests
以下の場合は２つとも実行される.

```
$ cargo test this_test_will
```

### Ignoring Some Tests Unless Specifically Requested
時間のかかるテストを `ignore` 属性で除外するよう注釈できる.

```rust
#[test]
fn it_works() {
    assert_eq!(2 + 2, 4);
}

#[test]
#[ignore]
fn expensive_test() {
    // code that takes an hour to run
}
```

`cargo test` を実行すると `1 ignored` と出力される.

```
running 2 tests
test expensive_test ... ignored
test it_works ... ok

test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

ignore 注釈のついたテストだけを実行することも可能.

```
$ cargo test -- --ignored
```

# Test Organization

- Rustのコミュニティでは, テストを単体テストと結合テストの２カテゴリで捉えている
- 単体テスト
  - 小規模
  - 個別に1回に1モジュールをテスト
  - 非公開のインターフェイスもテストすることがある
- 結合テスト
  - ライブラリ外から, 他の外部コード同様に自分のコードを使用
  - 公開インターフェイスのみ使用
  - 1テストにつき複数のモジュールを用いることもある

### Unit Tests

- 単体テストの目的:
  - 残りのコードから切り離して各単位のコードをテストし, コードが想定通りに動いたり動いていなかったりする箇所を迅速に特定する
- テスト対象となるコードと共に, srcディレクトリの各ファイルに置く
- いくつか慣習がある
  - 各ファイルにtestsという名前のモジュールを作りテスト関数を含ませる
  - そのモジュールをcfg(test)で注釈

### The Tests Module and #[cfg(test)]

- `#[cfg(test)]` 注釈をつけた tests モジュールがあると, コンパイラは cargo testを走らせた時にだけ, そのテストコードをコンパイルし実行するようになる.
  - コンパイルタイムとコンパイル後の成果物のサイズを節約
  - 結合テストに関しては, テスト対象コードとは別のディレクトリに作成するので注釈の必要がない

`cargo new --lib` で自動生成されるテストモジュールは次のようなもの:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

- cfg属性を注釈しておくと, コンパイラにある特定の設定オプションを与えられたときのみ（コンパイル対象に）含まれるようになる.
  - 今回は `cfg(test)` なので cargo test を実行したときのみ `mode tests` がコンパイル対象となる

### Testing Private Functions
Rustでは非公開関数をテストすることが可能となっている.
非公開関数を直接テストするべきかについては様々な討論があり, 
テストするか否かについては特に強制されていない.

```rust
pub fn add_two(a: i32) -> i32 {
    internal_adder(a, 2)
}
fn internal_adder(a: i32, b: i32) -> i32 { // 非公開関数
    a + b
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn internal() {
        assert_eq!(4, internal_adder(2, 2));
    }
}
```

上記では通常のコードと同様 tests モジュール内でも非公開関数 `internal_adder` を呼び出すことが可能となっている.

所感： 非公開関数を直接テストするべきかについて. 特に unit test を regression test などで利用する場合には, リファクタリングなどに伴うテストの保守性を考慮して決めることをおすすめする. 例えば, テスト対象の出力の構造や期待値が頻繁に変わる場合などは保守性が下がる.

### Integration Tests

- 結合テストの目的:
  - ライブラリのいろんな部分が共同で正常に動作しているかをテストする
- 結合テストではライブラリの公開APIの一部である関数しか呼び出すことができない
- 結合したコードのテストの範囲も同様に重要
  - 単体では正常に動くコードも結合した状態だと問題を孕む可能性がある

### The tests Directory
プロジェクトディレクトリのトップ階層, srcの隣にtestsディレクトリを作成する.

```
├── Cargo.lock
├── Cargo.toml
├── src
│   └── lib.rs
└── tests
```

tests 内に作成したファイルは, ファイルごとに個別の crate としてコンパイルされる.
例えば次のようなファイルを作成する.

```rust
extern crate adder;

#[test]
fn it_adds_two() {
    assert_eq!(4, adder::add_two(2));
}
```

`extern crate adder` により各々ライブラリをインポートする.
トップ階層に作成した `tests` は結合テスト用の特別なディレクトリとして扱われるので `#[cfg(test)]` は必要ない.
`cargo test` を実行すると単体テスト, 結合テスト, doc test の3種類がそれぞれ実行される.

```
running 1 test
test tests::internal ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-ce99bcc2479f4607

running 1 test
test it_adds_two ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

11.2 と同様に, 次のようにすれば特定のテストのみフィルタして実行可能.
この場合はファイル名によりフィルタされている.

```
$ cargo test --test integration_test
```

### Submodules in Integration Tests

- テスト対象となる機能に応じてテスト関数をグループ化することを想定し, testsディレクトリに2つ以上のファイルを作成してみる.
- ファイルを分けることにより個別のスコープを生成しやすくなる.
  - 例えば tests/common.rsを作成し, そこにsetupという名前の関数を配置して, tests 内の様々なファイルから利用することなどができる.
- テストがなくてもファイルがあればテスト結果が表示される
  - ファイル名を mod.rs とすることで結合テストファイルとして扱うことを回避できる
  - 例えば common という名前で参照したいなら `tests/common/mod.rs` とする

他のファイルの参照は（テストでない場合と同様）次のようにすれば良い.

```rust
extern crate adder;

mod common;

#[test]
fn it_adds_two() {
    common::setup();
    assert_eq!(4, adder::add_two(2));
}
```

### Integration Tests for Binary Crates

- バイナリクレートの場合
  - 特に `src/main.rs` ファイルのみを含み `src/lib.rs` ファイルを持たない場合
  - testsディレクトリに結合テストを作成することはできない
  - `extern crate` を使用しても `src/main.rs` ファイルに定義された関数をインポートすることはできない
- バイナリを提供するRustのプロジェクト（ちょっとわかりにくい. こういったプロジェクトの多くは？）
  - `src/lib.rs` ファイルに存在するロジックを呼び出す単純な `src/main.rs` ファイルがおいてある
  - 重要な機能は lib として実装し, `extern crate` を使用して結合テストでテストする
  - `src/main.rs` は少量のコードでテストする必要がない

### Summary

- Rust におけるテスト:
  - コードがどう機能すべきが限定する手段を提供する
  - さらに, 変更を加えた後でさえ想定通りにコードが機能し続けることを保証
- 単体テスト
  - ライブラリを個別にテスト. 非公開の実装詳細もテストできる
- 結合テスト
  - ライブラリのいろんな部分が連携して正常に動作することを確認
  - ライブラリの公開APIのみに対し, あたかも外部コードがそれを使用するのと同じ方法でコードをテスト
- テストは, 期待されるコードの振る舞いに関するロジックのバグを減らすのに重要
